### ISSUE TITLE
Should ReliableSpout extend Spout?

### ISSUE THREAD

**Issue by mal** [pystorm/pystorm#49]
Reading through the code (looks really good by the way, we've been using `storm.py` for years, not knowing this was here :sob:) it reads as if `ReliableSpout` is expecting to inherit from `Spout` rather than `Component`? In addition to missing a `_run` loop, which I suspect is fine being identical to `Spout`'s, it also misses the stubbed out methods called from it (`_run`): `activate`, `deactivate` and `next_tuple`.

It does function fine inheriting from `Component`, since the missing methods are only called from the also missing `_run` loop, hence the questioning nature of this issue.

If its current inheritance is intentional a pointer to what the correct usage for it would be would be very appreciated, thanks! :slightly_smiling_face:

**Comment by msukmanowsky** [comment]
@dan-blanchard this one is for you. From a quick glance, it does seem like it `ReliableSpout` could easily extend `Spout` and override necessary methods.

**Comment by dan-blanchard** [comment]
Thanks for catching this @mal. It doesn't actually matter for most of us, since nearly everyone uses `streamparse` and not `pystorm` directly. The only reason it works via `streamparse` is because we [use multiple inheritance there](https://github.com/Parsely/streamparse/blob/cb72e1107096df9b80915fad4ee0fd1d930c7b59/streamparse/storm/spout.py#L134) that fixes this.

**Comment by mal** [comment]
Thanks, really appreciate you taking the time to update it 👍 We've just discovered `pystorm` and `streamparse` after years using the vanilla `storm.py`, and while we may yet end up on `streamparse` in the end, for now working  with `pystorm` is huge step forward all on it's own! 😁
